#!/bin/bash

if ! [ -x "$(command -v brew)" ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo "homebrew is already installed..."
fi


brew bundle --verbose

gem install tmuxinator

npm install -g newman

mkdir ~/bin
cd ~/bin
git clone https://github.com/olivierverdier/zsh-git-prompt.git
