#!/bin/bash

if ! [ -x "$(command -v brew)" ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo "homebrew is already installed..."
fi

brew install tmux








gem install tmuxinator


